### ISSUE TITLE
Logo images are missing alt attributes

### ISSUE THREAD

**Issue by jrha** [GOCDB/gocdb#117]
Flagged by htmlproofer:
>   *  image img/STFC.jpg does not have an alt attribute (line 59)
>  *  image img/egi_logo.jpg does not have an alt attribute (line 59)
>  *  image img/eu.jpg does not have an alt attribute (line 59)

These should be fixed to improve accessibility.

**Comment by jrha** [comment]
It seems that the majority (maybe all) images are missing `alt` attributes, but it's up to you to decide which are meaningful.

**Comment by tofu-rocketry** [comment]
Fixed in #116 (2b25e64ab2fab4a4067aad3).
