### ISSUE TITLE
Need non-admin Service Types views

### ISSUE THREAD

**Issue by tofu-rocketry** [GOCDB/gocdb#126]
There is an admin-only Service Types view that lists all the available service types with their descriptions and links to individual service type pages that list all the services for that type.

It would be useful for something similar to be made available to non-admins (without add/edit/delete) - currently these seem to be the only (unmaintained) places to see service type descriptions:
- https://wiki.egi.eu/wiki/GOCDB/Input_System_User_Documentation#Service_types
- https://github.com/OGF-GLUE/Enumerations/blob/master/ServiceType_t.csv

**Comment by gregcorbett** [comment]
This doesn't completely remove the need for a non-admin Service Type page, but for completeness: 

- There is an [API endpoint](https://wiki.egi.eu/wiki/GOCDB/PI/get_service_types_method) which exposes this information,
- This [external page](https://poem.egi.eu/ui/public_servicetypes) parses that API endpoint to show the service types in GOCDB and their descriptions.
