### ISSUE TITLE
misslabled button on Add_Service_Group_SEs page

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#131]
The add button on the Add_Service_Group_SEs page is labelled " "Add SEs to service group", it would more appropriately be labelled "add services to service group".

**Comment by tofu-rocketry** [comment]
As reported in [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=137673).

**Comment by gregcorbett** [comment]
Do we want to change other reference to "SE" on that page to "service" at the same time?

i.e.
> Please ensure the _service_ administrators are aware you are adding their _services_ to this service group.
