### ISSUE TITLE
Consider improving email regex

### ISSUE THREAD

**Issue by jrha** [GOCDB/gocdb#147]
As mentioned in #146, the base regex may be too restrictive as it definitely does not allow for Unicode characters in addresses, which may or may not be allowed anyway.

It might also be worth seeing whether PHP's built-in regex filter would be good enough:
```php
filter_var($email, FILTER_SANITIZE_EMAIL);
```

The [HTML5 spec says](https://html.spec.whatwg.org/#e-mail-state-(type=email)) an email address is:
```regex
/^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/
````

**Comment by GRyall** [comment]
The current validation in GOCDB is built around the use of Regular Expressions. Using filter_var would be better, but implementing an improved regex (like the one from the HTML5 spec)  would be quicker and easier, so I suggest doing that.
