### ISSUE TITLE
 'production => monitored' rule should be a property of the ServiceType in the database and not hardcoded.

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#156]
I want to be able to throw up databases in a quattorized fashion before I tackle this, but if anyone else wants to tackle it sooner I won't stop them.

**Comment by tofu-rocketry** [comment]
You mean rather than having a hardcoded list of ServiceTypes where the rule is not enforced?

**Comment by gregcorbett** [comment]
> You mean rather than having a hardcoded list of ServiceTypes where the rule is not enforced?

Indeed

**Comment by ineilson** [comment]
After talking to Greg: the proposal (as I understand it) is to add a ProductionMonitorException table to the schema:

**ProductionMonitorException:**
+ScopeId
+ServiceTypeId

for any production service instance, the monitoring flag can only be off if scope and servicetype match an entry in this table.
How the table is built is tbc, but probably by adding list of 'exception allowed' ServiceTypes on Scope edit/create dialogues.
If a conflict is found when editing a Service instance with multiple scopes, the edit is disallowed and must be sorted out externally. Which possibly means this should only apply only to reserved scopes?

**Comment by GRyall** [comment]
Remember that everything happens through Doctirne - so we don't do the database design directly. so it would likely be a many to many property of Scopes - monitredProductionServiceTypeExceptions or similar. It would then be a case of checking if the service types was in there, rather than checking the config xml.

**Comment by gregcorbett** [comment]
> Remember that everything happens through Doctirne - so we don't do the database design directly. so it would likely be a many to many property of Scopes - monitredProductionServiceTypeExceptions or similar.

Good point!

> It would then be a case of checking if the service types was in there, rather than checking the config xml.

**As if** it's currently stored in configuration...

> Which possibly means this should only apply only to reserved scopes?

Does it? I don't follow the logic here...

**Comment by ineilson** [comment]
> 
> 
> > Remember that everything happens through Doctirne - so we don't do the database design directly. so it would likely be a many to many property of Scopes - monitredProductionServiceTypeExceptions or similar.
> 
> Good point!
Thanks for the reminder :-)
> 
> > It would then be a case of checking if the service types was in there, rather than checking the config xml.
> 
> **As if** it's currently stored in configuration...
Not sure where the config xml comes into this?
> 
> > Which possibly means this should only apply only to reserved scopes?
> 
> Does it? I don't follow the logic here...
Well, one month on, neither do I. Mitigation: I said "possibly".
