### ISSUE TITLE
Wording around downtimes should be more consistent

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#169]
As per [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=141188):
- The site level view here https://goc.egi.eu/portal/index.php?Page_Type=Site&id=335 uses the phrase "Downtime Affecting XXXX's SEs"
- Whereas this view on downtimes https://goc.egi.eu/portal/index.php?Page_Type=Site_Downtimes&id=335 uses the phrase "Downtimes Affecting XXXX's Services"

I think the best language is to use in all cases when referring to downtimes is "Downtimes Affecting XXXX's Services and Endpoints".

**Comment by ineilson** [comment]
I think the posessive apostrophe is somewhat pedantic and distracting in this context. Suggest: remove in both examples. 

Also, the all-downtimes header now becomes rather cumbersome multi-line.

So, suggest changing -

![gocdb 2019-09-16 121742](https://user-images.githubusercontent.com/20706670/64956190-f25be400-d881-11e9-87aa-ec98ebf5fbab.png)

- to - 

![gocdb 2019-09-16 125704](https://user-images.githubusercontent.com/20706670/64956212-ff78d300-d881-11e9-8e73-2fc9e761452f.png)

**Comment by ineilson** [comment]
Or, more consistent with other pages -

![image](https://user-images.githubusercontent.com/20706670/64961896-5be1ef80-d88e-11e9-9463-31a01380296e.png)

**Comment by tofu-rocketry** [comment]
That last one looks good.

**Comment by gregcorbett** [comment]
> 
> 
> That last one looks good.

Indeed 😄 I'd go with that.

**Comment by ineilson** [comment]
Quick snoop around other Downtime pages for cosmetic changes. Any idea why the header width is restricted (width: 45em) on the summary page? Nothing obvious to me. -

![downtimes1 2019-09-17 094542](https://user-images.githubusercontent.com/20706670/65026589-c51a3f00-d930-11e9-8648-e835a2d4dd2c.png)

Propose quick fix by removing width spec. ? -

![downtimes2 2019-09-17 094542](https://user-images.githubusercontent.com/20706670/65026641-dd8a5980-d930-11e9-987c-e275999353ca.png)

**Comment by gregcorbett** [comment]
> Any idea why the header width is restricted (width: 45em) on the summary page? 

Nope, maybe the entire page width was once `width: 45em`...

> Propose quick fix by removing width spec. ? -

what happens if remove it and have an incredible long title? Does it stretch the entire page?

**Comment by ineilson** [comment]
No it seems to manage it sensibly -

![image](https://user-images.githubusercontent.com/20706670/65226987-c332b600-dabf-11e9-9c41-e40b44036fd6.png)

**Comment by gregcorbett** [comment]
Fixed in #182
