### ISSUE TITLE
Authentication attributes box on user page shows the AuthenticationRealm of the logged in user, not the user being viewed.

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#203]
This was not the behaviour I was expecting. 

I thought it displayed how the user being viewed logs into GOCDB, but doing some digging I don't believe this information is even stored per user...

**Comment by GRyall** [comment]
For non-admins, the only user page accessible is the one for that user (accessed with the 'view details' link). The page is then reused for the admin view on all users. I suggest we simply hide the box when you are not viewing yourself. 

Given the above, I am labelling this as an enhancement (no bug is visible to end users).

**Comment by gregcorbett** [comment]
> For non-admins, the only user page accessible is the one for that user (accessed with the 'view details' link). 

Non-admin users can view any other user page, so it is a bug visible to end users.

> I suggest we simply hide the box when you are not viewing yourself.

That seems like a sensible fix.
