### ISSUE TITLE
missing text on api credential success page

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#219]
After adding a new Write API credential, the identifier string is not displayed on the success page
![image](https://user-images.githubusercontent.com/4125374/80368021-f8885900-8883-11ea-9423-4846a18c93e1.png)

Either the DN needs adding after the word 'identifier' or the words 'with identifier' need deleting. I suspect the former was the intention and there is a minor bug somewhere.

**Comment by gregcorbett** [comment]
For reference, the relevant files responsible for this are:
- https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/controllers/site/add_api_auth.php
- https://github.com/GOCDB/gocdb/blob/dev/htdocs/web_portal/views/site/added_api_auth.php
