### ISSUE TITLE
GT-141 pre-select site on add downtime page

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#229]
Following some confusion from a user, I suggest the following enhancements to the add downtime page:

- When a user access the page via a site, pre-select the site in the box (it only shows that site anyway)
- When a user accesses the page via a service pre-select the parent site and that service

Users can still change there selection, but it reduces the number of clicks for them and makes clear they have to select something.

**Comment by tofu-rocketry** [comment]
Hmm, I know I might be considered an "expert user", but I've never had a problem with selecting a site and service on the the downtime page. I thought it was quite clear.

It says "Select Affected Site" and then "Select Affected Services+Endpoints (Ctrl+click to select)".

I guess it's a nice convenience feature.

**Comment by GRyall** [comment]
It doesn't get worse for having it and should be easy enough to implement
