### ISSUE TITLE
Consider future of changeLog.txt

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#230]
We currently have changeLog.txt, which tracks GOCDBB versions. Now we are on GitHub maybe we don't need this. Either that or it needs updating!

**Comment by tofu-rocketry** [comment]
Is is noted in the file that future release notes are on GitHub, so updating it seems unnecessary:
```
For a continuing changelog, please see:
https://github.com/GOCDB/gocdb/releases 
```
The content should be kept for reference, but not sure how best to handle that. Adding it retrospectively to GH Releases will put them out of order as it sorts by latest added, which is a bit annoying.
