### ISSUE TITLE
Clickable extension property url

### ISSUE THREAD

**Issue by ineilson** [GOCDB/gocdb#232]
If an extension property value references a known document type (.xml, .json etc) it would be a convenience if the UI presented the property value as a clickable url. i.e. make the highlighted text clickable -
![image](https://user-images.githubusercontent.com/20706670/86587626-e0b70a80-bf81-11ea-94a2-d8514994144b.png)

**Comment by tofu-rocketry** [comment]
That would be useful, but should this not be based on the scheme (i.e. HTTP/HTTPS) rather than the path extension? You can't rely on the path to define what the document type of a resource is (and some view it as bad practice).

**Comment by ineilson** [comment]
Maybe, and one should also consider possibility of security issues, but I don't think all extension properties are necessarily going to point to browser-renderable content, so using the protocol won't be sufficient.

**Comment by gregcorbett** [comment]
Sounds like a useful enhancement to me :).

Although users can't upload documents as extension property values, just "pointers" to where that document can be found. So wouldn't it have to be done based on protocol (i.e. HTTP/HTTPS)?

**Comment by ineilson** [comment]
OK. All values matched as URLs could be made hyperlinks. The user would decide if following the link is likely to be useful to them or not.

**Comment by tofu-rocketry** [comment]
> ... I don't think all extension properties are necessarily going to point to browser-renderable content, so using the protocol won't be sufficient.

Sure, but unless we test the URL, the only thing we can rely on is the protocol/scheme. As you say in your last comment, it'll be up to the user if it's useful.

> Maybe, and one should also consider possibility of security issues, ...

Mitigate with an external link warning page?
