### ISSUE TITLE
Adding/Editing a Site fails when longitude or latitude are empty on MariaDB

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#257]
I don't have a MariaDB instance to hand to confirm the exact error, but it was something along the lines of "Invalid float", as if a `0` was getting passed to the database and it wanted `0.0`

**Comment by ineilson** [comment]
@gregcorbett I believe this can now be closed having been merged (into a non-default branch).

**Comment by gregcorbett** [comment]
Good catch! This was fixed in https://github.com/GOCDB/gocdb/pull/275
