### ISSUE TITLE
Prevent downtimes starting in 24 hours from being deleted.

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#269]
Highlighted via [GGUS](https://ggus.eu/index.php?mode=ticket_info&ticket_id=149777).

Whilst a `downtime` can't be edited within 24 hours of it's start time "because it has been read in by other systems", it can be deleted. This seems inconsistent.

Checks on what can and can't be done to `downtimes` are split across both the view and controller layer, I would suggest this check is implemented at the controller level.

**Comment by ineilson** [comment]
Would it be useful to flag that somebody at least wanted to delete the downtime, or can that already be done?

**Comment by gregcorbett** [comment]
I think it should be logged that some form of request to the delete_downtime page was made and it should log the attempt was a failure (and some sort of appropriate http status code, maybe `400 Bad Request`)
