### ISSUE TITLE
Update to new EGI AUP

### ISSUE THREAD

**Issue by ineilson** [GOCDB/gocdb#285]
EGI approved a new AUP effective from 01/06/2020. The GOCDB AUP should be updated to reflect this change -
https://documents.egi.eu/public/ShowDocument?docid=3600

**Comment by ineilson** [comment]
To be implemented as a local_config.xml-configurable url (https: or file:) for the content. For the EGI case, at present, this will be the EGI document https://documents.egi.eu/public/RetrieveFile?docid=3600&filename=EGI-SPG-AUP-V3.pdf&version=3
At the same time, make the equivalent change for the Privacy Notice.
Mark the link tag for opening in another tab/window.

**Comment by ineilson** [comment]
The EGI document repository (referenced above) requests a client certificate. This is poor UX if, like me, you have two valid certificates loaded or have set the browser to 'always ask', since GOCDB has asked (is this correct for the landing page?). I suggest that we download a PDF copy of the latest policy and link to that. It can still be outside of the git tree. Thoughts @gregcorbett ?

**Comment by tofu-rocketry** [comment]
It didn't ask me for a cert and I don't think I've logged into it recently. We should use the most public and permanent link to the document. The direct link to the PDF might not be the most appropriate.

**Comment by tofu-rocketry** [comment]
This is the permalink: https://documents.egi.eu/document/3600

**Comment by ineilson** [comment]
That's the link to document page, we want a link to a PDF version
