### ISSUE TITLE
500 error on add NGI admin functionality

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#293]
When using the admin functionality to add an NGI, a 500 error is returned. So far this has only been seen on devlopment environments. @ElliottKasoar reports the error appears linked to https://github.com/GOCDB/gocdb/blob/dev/lib/Gocdb_Services/NGI.php#L525

I suggest checking the behaviour of pre-pod. If it works fine on pre-prod then it is likely some missing required data relating to scopes. If it doesn't then there has been some changer to the underlying logic that isn't reflected in the add NGI admin logic

**Comment by gregcorbett** [comment]
This might be fixed, or otherwise related, to #264

**Comment by gregcorbett** [comment]
I believe this is now fixed in `dev`.
