### ISSUE TITLE
Unaccentuate "unaccentuated"

### ISSUE THREAD

**Issue by tofu-rocketry** [GOCDB/gocdb#303]
Pretty sure these pages should say "unaccented" rather than "unaccentuated", right?

`htdocs/web_portal/views/user/edit_user.php`
`htdocs/web_portal/views/user/register.php`

There's two pages with two occurrences each: https://github.com/GOCDB/gocdb/search?q=unaccentuated

(Spotted in the screenshots in [this ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=153994).)

**Comment by gregcorbett** [comment]
Just assigning this to me so no one else picks it up as there is a PR open.
