### ISSUE TITLE
Move to newer version of Doctrine (2.5 at least)

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#335]
The version of Doctrine we currently use is no longer supported (https://www.doctrine-project.org/projects/orm.html). We were stuck on it because the next version (2.5) required php 5.4  or greater. With #238 we removed php 5.3 support and so can now migrate upwards. This may be true for other components as well.

Pretty careful testing would be needed

**Comment by gregcorbett** [comment]
The dream would be going all the way to 2.12

**Comment by ineilson** [comment]
@GRyall 
> Pretty careful testing would be needed

Beyond the 'unit' tests, checking some arbitrary functionality through the web+PI interfaces, and looking for errors/warnings in logfiles, do you have suggestions for what else 'Pretty careful' might mean in this context? (ORM update to 2.5.14 appears, at first glance, to be unproblematic.)

**Comment by GRyall** [comment]
> @GRyall
> 
> > Pretty careful testing would be needed
> 
> Beyond the 'unit' tests, checking some arbitrary functionality through the web+PI interfaces, and looking for errors/warnings in logfiles, do you have suggestions for what else 'Pretty careful' might mean in this context? (ORM update to 2.5.14 appears, at first glance, to be unproblematic.)

Mainly I meant "checking some arbitrary functionality through the web+PI interfaces"

**Comment by gregcorbett** [comment]
We are running ORM 2.6, getting to a supported version is tracked in https://github.com/GOCDB/gocdb/issues/337

**Comment by GRyall** [comment]
🥳
