### ISSUE TITLE
Layout can be wonky on ServiceGroup page

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#374]
I'm not sure if it's caused by a ServiceGroup with a particularly long name, a particularly long description or something else all together - but it's possible the layout can be wonky for a ServiceGroup.

For example: https://goc.egi.eu/portal/index.php?Page_Type=Service_Group&id=3233

![image](https://user-images.githubusercontent.com/2488355/182094607-7808203e-b33e-4fc6-8b1a-4a4d92c60cfa.png)

Looking at that example, I suspect it's an issue with the length of the description, maybe we can force some line breaks?

**Comment by tofu-rocketry** [comment]
Confirmed as being due to the long description. Locally shortened the description of a service group that was showing the issue using Firefox dev tools:

![image](https://user-images.githubusercontent.com/4836233/182124097-fe5f471b-9e4a-435a-8f8f-637d334afaa3.png)

**Comment by gregcorbett** [comment]
This may only affect the ServiceGroup page, as it doesn't seem to affect the Site page.
