### ISSUE TITLE
Improve clarity of text on account linking/recovery page

### ISSUE THREAD

**Issue by gregcorbett** [GOCDB/gocdb#376]
"Details of account to be linked or recovered" could be reworded or followed by something along the lines of: "These details are for the account you wish to regain access to or link you current identity to. Do not enter the details of your current identity."

Is there benefit of showing the current login details?, i.e.:

> Your current ID string (e.g. certificate DN) is: ...
> Your current authentication type is: ...

"What is identity linking?" / "What is account recovery?" could be moved to after the choice of "Authentication type" and only display the relevent one. Maybe in this case we don't need the final bullet point of each section.

**Comment by gregcorbett** [comment]
It should also be clearer that the identity linking doesn't support one account having mutliple identifiers of the same type i.e. two X.509 certificate DNs.

**Comment by gregcorbett** [comment]
related [GGUS Ticket](https://ggus.eu/index.php?mode=ticket_info&ticket_id=158446).

**Comment by gregcorbett** [comment]
> It should also be clearer that the identity linking doesn't support one account having mutliple identifiers of the same type i.e. two X.509 certificate DNs.

Maybe identity linking could support this #378.

**Comment by gregcorbett** [comment]
related [EGI JIRA Issue](https://jira.egi.eu/browse/EGITCB-396).

**Comment by tofu-rocketry** [comment]
May need to split this into separate pages for linking and recovery. Would be more logical for the user.
