### ISSUE TITLE
Legacy "X509" type identifier in API credentials

### ISSUE THREAD

**Issue by ineilson** [GOCDB/gocdb#390]
The TYPE identifier stored in legacy (pre 5.10.0) is "X509", not the standardised "X.509", which causes a failure to update the ownership of the credential, since this conditional is never satisfied -

https://github.com/GOCDB/gocdb/blob/31a415a89202a29c446bd4e21936d91968ea8317/lib/Gocdb_Services/Site.php#L1458

**Comment by gregcorbett** [comment]
Given how frequently these legacy API credentials are used, I'm inclined not to fix this. They'll be deleted soon™️ if they aren't used anyway.

If a user wants these API credentials to work and notices they don't, we can manually edit the DB entry to change "X509" to "X.509".
