### ISSUE TITLE
Incorrect instruction in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rowan04** [GOCDB/gocdb#414]
In the CONTRIBUTING.md file, the following instructions are wrong:

https://github.com/GOCDB/gocdb/blob/f94e9807592ab18ee4318758c94329d5e6b95bf4/CONTRIBUTING.md?plain=1#L70

https://github.com/GOCDB/gocdb/blob/f94e9807592ab18ee4318758c94329d5e6b95bf4/CONTRIBUTING.md?plain=1#L66

It should say to push to your fork, not to origin.

Looking at it,  the file hasn't been updated in 7 years - maybe it needs an update?

**Comment by gregcorbett** [comment]
`origin` is typically the developers fork, with `upstream` being the organisation repository - i.e. https://github.com/GOCDB/gocdb in our case.

**Comment by rowan04** [comment]
> `origin` is typically the developers fork, with `upstream` being the organisation repository - i.e. https://github.com/GOCDB/gocdb in our case.

I see - when i used origin on one of my pushes it failed, and i had to use rowan. thats why i did the issue.
