### ISSUE TITLE
 Check - duplicate keys allowed with last key taking precidence

### ISSUE THREAD

**Issue by davidmeredith** [GOCDB/gocdb#46]
In this example, 'aa' was added/updated with value 'aa2' 

```
curl -i -k --cacert $cacert --cert $mycert --key $mykey -X PUT https://localhost/gocdbpi/V5/site/335/ExtensionProperties -d '{"aa":"aa1","aa":"aa2","cc":"cc"}'
HTTP/1.1 200 OK
```

**Comment by GRyall** [comment]
This is a because the provided JSON is invalid - JSON does not permit duplicate keys. Arguably PHPs json_decode function should fail, rather than choosing one of the two pairs. The only way of fixing this is to implement our own JSON parser, which seems quite heavyweight to deal with user error.

**Comment by GRyall** [comment]
Though we could possibly right some kind of JSON parser to look for duplicate keys, again - heavyweight

**Comment by tofu-rocketry** [comment]
Shall we close this?
