### ISSUE TITLE
Enrich and personalise emails

### ISSUE THREAD

**Issue by jrha** [GOCDB/gocdb#64]
We all just received the following really generic emails, it would be nice if they contained a bit more information, for example, my name, the user-name that requires attention, what "attention" they require.
This might also help it look less like a phishing attempt.

> Dear GOCDB User,
> 
> A user has requested a role that requires attention.
> 
> You can approve or deny this request here:
> 
> https://goc.egi.eu/portal/index.php?Page_Type=Role_Requests
> 
> Note: This role may already have been approved or denied by another GocDB User

**Comment by gregcorbett** [comment]
A start was made [here](https://github.com/gregcorbett/gocdb/tree/enrich_role_emails)

**Comment by gregcorbett** [comment]
Could be tackled at the same time as #163
