### ISSUE TITLE
Read only mode warning appears in wrong place

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#65]
From the 5.7 release the read only mode warning appears next to, instead of beneath, the version text

**Comment by tofu-rocketry** [comment]
Message seems to be placed here: https://github.com/GOCDB/gocdb/blob/1fe9d2b8e45320757423143c1dd45b69fba1e587/htdocs/web_portal/components/Draw_Components/draw_page_components.php#L39

**Comment by gregcorbett** [comment]
> From the 5.7 release the read only mode warning appears next to, instead of beneath, the version text

Doesn't it appear beneath _now_? (see [goc.dl.ac.uk](goc.dl.ac.uk), screenshot below)

![Untitled](https://user-images.githubusercontent.com/2488355/91147116-bba46580-e6af-11ea-96bc-f2aa80ccdbde.png)

**Comment by tofu-rocketry** [comment]
The failover has this HTML `<br>Read_only_Mode` which isn't in the repository. Is that a local change to the file `read_only_warning.html`?

**Comment by tofu-rocketry** [comment]
c.f. my PR #251

**Comment by gregcorbett** [comment]
>  Is that a local change to the file `read_only_warning.html`?

ah yes, yes it is.
