### ISSUE TITLE
Whitespace trimming on email (all?) fields

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#82]
It would improve the user experience if we were to trim leading and trailing white space from submitted email addresses in forms (this has been pointed out to me for the add/edit service ones in particular). The error message when such white space is present can be unclear.

**Comment by tofu-rocketry** [comment]
Could this be extended to all fields? In particular I've seen this cause problems many times for DNs and [at least once](https://ggus.eu/index.php?mode=ticket_info&ticket_id=134788) for IP addresses.

**Comment by tofu-rocketry** [comment]
As you pointed out before, this should only apply to new/updated values, not existing values.

**Comment by tofu-rocketry** [comment]
Can we get this change prioritised please? Tracking down trailing whitespace in DNs takes up a significant amount of our time when dealing with GGUS tickets.
