### ISSUE TITLE
Authentication attributes box on user page does not match theme of page

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#84]
The style of this box does match the rest of the page. From a user perspective, it is unclear what this box means.

![image](https://cloud.githubusercontent.com/assets/4125374/23172692/8a6a9960-f84e-11e6-8e84-835c20f5ebb0.png)

**Comment by gregcorbett** [comment]
related issue: #203, possibly #84 isn't worth solving...

**Comment by GRyall** [comment]
see my comment on #203, I think this is worth solving.
