### ISSUE TITLE
Add_downtime link fails for administrators

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#87]
Probably a time-out because of a very large query.

**Comment by davidmeredith** [comment]
Confirmed, large query causes out of mem: 

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 116 bytes) in /usr/share/gocdbGit/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2727

**Comment by tofu-rocketry** [comment]
Is this potentially a problem if a user has more than one NGI/ROD permission or for someone with Project permissions?

**Comment by GRyall** [comment]
Potentially, it is hard to be certain without testing.

**Comment by gregcorbett** [comment]
Just hit this, only panicked for a brief moment. #admintroubles

**Comment by ineilson** [comment]
I've been unable to replicate this, either as an administrator, by taking many NGI roles, or by halving PHP memory.

**Comment by GRyall** [comment]
I can confirm I also no longer get this on the current live site - Did we significantly increase some allowed memory factor somewhere in the PHP config (I have a half memory of doing this when working on ?The write API?)?

**Comment by ineilson** [comment]
I chopped it back to 64M from 128M on a test instance (with production dataset) and still could not reproduce the error.

**Comment by tofu-rocketry** [comment]
Can this and the other issue be closed then?

**Comment by gregcorbett** [comment]
I would say so
