### ISSUE TITLE
Improve handling of reserved scopes

### ISSUE THREAD

**Issue by GRyall** [GOCDB/gocdb#99]
Reserved scopes are currently set through local_info.xml. To me this feels more like a property of the scope and I think it should be a boolean as part of the schema.

**Comment by ineilson** [comment]
If an isReserved property is added to the schema, does it make sense to add isDefault (i.e. EGI) at the same time? (assuming "uniqueness" can be enforced)

**Comment by GRyall** [comment]
Possibly. On the one hand that would be the better way of doing it. On the other that was always a bit of a horrible cludge and I am not sure we should build it in

**Comment by gregcorbett** [comment]
Just assigning the issue to ineilson for completeness, there's already an PR open that fixes the issue.
